name: iOS CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run xcodebuild
        run: |
          SIM_ID=$(xcodebuild -showdestinations -scheme "GroceryWatch Watch App" -project ios/GroceryWatch/GroceryWatch.xcodeproj | grep "watchOS Simulator" | grep -v "Placeholder" | head -n 1 | awk -F'id:' '{print $2}' | awk -F',' '{print $1}' | tr -d ' ')
          echo "Using Simulator ID: $SIM_ID"
          xcodebuild test -scheme "GroceryWatch Watch App" -project ios/GroceryWatch/GroceryWatch.xcodeproj -destination "platform=watchOS Simulator,id=$SIM_ID"
