name: iOS CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inspect Simulators
        run: |
          xcrun simctl list
          xcodebuild -showdestinations -scheme "GroceryWatch Watch App" -project ios/GroceryWatch/GroceryWatch.xcodeproj || true
          exit 1
